<template>
  <div>
    <h1>Data protection</h1>
    <p>
      The University of Applied Sciences and Arts Northwestern Switzerland FHNW places great importance on correct and up-to-date information.
      Some or all of the content on our website may therefore need to be amended, deleted or (occasionally) no longer shown.
    </p>
    <h2>Personal information</h2>
    <p>The FHNW is committed to the targeted and sparing use of personal information. The information collected is used only for the intended respective purpose.</p>
    <p>
      The personal information stored remains within the sovereignty of the FHNW. Information is stored carefully and protected against third-party access.
      We secure information by means of technical and organisational measures in keeping with the latest developments.
      We never disclose personal information to third parties, unless the law requires us to do so or we have obtained express permission.
    </p>
    <h2>Cookies</h2>
    <p>Cookies are text files which are stored temporarily or permanently on your computer and which, for example, enable your use of the website to be analysed.</p>
    <p>
      You can entirely or partially prevent the cookies from being stored on your computer by adjusting the corresponding settings in your browser application.
      However, please be aware that if you do so, you may no longer be able to use all of the functions on this website.
    </p>
    <h2>Web analysis and re-/marketing by Google</h2>
    <h4>Google Analytics</h4>
    <p>
      The FHNW uses the Google Analytics web analysis service to receive information about how our website is used.
      Google Analytics uses cookies. The information generated by cookies is transmitted to a Google server in the USA. G
      oogle operates its own privacy policy.
    </p>
    <p>The FHNW uses Google Analytics only with IP anonymisation enabled. The IP address transmitted by the user’s browser is not combined with any other Google data.</p>
    <p>
      Users are not only able to prevent the storage of cookies, but – by downloading and installing the browser plugin provided under the following link – also the collection
      by Google of the data generated by the cookie and related to your use of the online service and the processing of this data by Google: » <a href="http://tools.google.com/dlpage/gaoptout?hl=en">http://tools.google.com/dlpage/gaoptout?hl=en</a>
    </p>
    <h4>Google Ads and Google conversion tracking</h4>
    <p>
      The FHNW uses Google Ads and conversion tracking. Ads and conversion tracking enable the FHNW to statistically record the use of its websites in order to optimise them. With conversion tracking, a cookie is set on your end device by Google when you visit a FHNW website by clicking on a Google ad.
      Conversion tracking is used to compile statistics and not to identify you personally. The information about which Google ads and interactions users use to visit the FHNW websites enables the FHNW optimise the way it delivers information.
    </p>
    <h4>Google Tag Manager</h4>
    <p>
      The FHNW uses Google Tag Manager for the administration of 'website tags'. This technology allows e.g. Google Analytics and other marketing analysis services to be incorporated into the online offering.
      The Tag Manager itself, which implements the tags, does not process any of the user's personal information. With regard to the processing of the user's personal information, please refer to the following descriptions of Google services.
    </p>
    <h4>Google privacy policy and information</h4>
    <p>Google operates its own privacy policy:</p>
    <p>» <a href="https://policies.google.com/privacy?hl=en">Google Privacy Policy & Google Terms of Service</a></p>
    <p>» <a href="https://policies.google.com/technologies/ads?hl=en">Use of data for advertising purposes</a></p>
    <p>Guidelines relating to the use of Google Tag Manager:</p>
    <p>» <a href="https://www.google.com/tagmanager/use-policy.html">https://www.google.com/tagmanager/use-policy.html</a></p>
    <h2>Third party services</h2>
    <p>
      The FHNW deploys content and service offers from third-party providers, e.g. to integrate videos, plug-ins and fonts, as well as retargeting technologies to tailor the online offer more closely to users.
      Retargeting technologies make it possible to address users, who have shown interest in the FHNW’s websites and the offers presented there, with information in a targeted manner.
      Retargeting is done on the basis of a cookie-based analysis of user behaviour.
    </p>
    <p>
      There follows an overview of third-party providers and their contents, as well as links to their privacy policies, which contain further information on the processing of data and, mentioned here in places, opt-out possibilities.
      The opt-in/opt-out status of all common online marketing systems can be viewed and edited via Your Online Choices' cookie management.
    </p>
    <h4>CleverReach</h4>
    <p>This website can use the CleverReach service platform for mail-outs. This is provided by CleverReach GmbH & Co. KG, Mühlenstr. 43, 26180 Rastede, Germany.</p>
    <p>» <a href="https://www.cleverreach.com/en-de/privacy-policy/">Privacy policy</a></p>
    <h4>Facebook</h4>
    <p>
      This website can use functions of the Facebook service. These functions are provided by Facebook Inc., 1601 S. California Ave, Palo Alto, CA 94304, USA. They allow us to show you targeted, personalised and interest-based advertisements.
      Facebook matches up this data with your personal Facebook user account in line with its Data Policy.
    </p>
    <p>If you want to prevent Facebook from showing you advertisements using the remarketing features, you can declare this in your Facebook account settings.</p>
    <p>» <a href="https://www.facebook.com/privacy/policy/?entry_point=data_policy_redirect&entry=0">Privacy policy</a></p>
    <p>» <a href="https://www.facebook.com/adpreferences/?entry_product=ad_settings_screen"> Privacy settings</a></p>
    <h4>Google Fonts</h4>
    <p>This website uses 'web fonts' for the uniform display of fonts. These are provided by Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA.</p>
    <p>» <a href="https://policies.google.com/privacy">Privacy policy</a></p>
    <h4>Instagram</h4>
    <p>
      This website can use functions of the Instagram service. These functions are provided by Instagram Inc., 1601 Willow Road, Menlo Park, CA, 94025, USA.
      If you are logged into your Instagram account, clicking the Instagram button links the contents of our pages to your Instagram profile.
      This allows Instagram to associate your visit to our pages with your user account.
      Please note that we as providers of the pages have no knowledge of what data is transmitted or of what Instagram does with it.
    </p>
    <p>» <a href="https://privacycenter.instagram.com/policy/?entry_point=ig_help_center_data_policy_redirect">Privacy policy</a></p>
    <h4>Issuu</h4>
    <p>This website can use functions of the Issuu service. These functions are provided by Issuu Inc., 131 Lytton Ave, Palo Alto, CA 94301, USA.</p>
    <p>» <a href="https://issuu.com/legal/privacy">Privacy policy</a></p>
    <h4>LinkedIn</h4>
    <p>
      This website can use functions of the LinkedIn service. The provider is the LinkedIn Corporation, 2029 Stierlin Court, Mountain View, CA 94043, USA.
      A link is established to LinkedIn servers every time you access one of our pages that contain LinkedIn features. This informs LinkedIn that you have visited our website with your IP address.
      If you click the LinkedIn "Share this page" button and are logged into your LinkedIn account, LinkedIn will be able to associate your visit to our site with you and your user account.
      Please note that we as providers of the pages have no knowledge of what data is transmitted or of what LinkedIn does with it.
    </p>
    <p>» <a href="https://www.linkedin.com/legal/privacy-policy">Privacy policy</a></p>
    <p>» <a href="https://www.linkedin.com/psettings/guest-controls/retargeting-opt-out">Opt-out</a></p>
    <h4>OpenStreetmap</h4>
    <p>This website can use maps of the OpenStreetmap service. These functions are provided by the OpenStreetMap Foundation, 132 Maney Hill Road, Sutton Coldfield, West Midlands, B72 1JU, United Kingdom.</p>
    <p>» <a href="https://wiki.osmfoundation.org/wiki/Privacy_Policy">Privacy policy</a></p>
    <h4>SlideShare</h4>
    <p>This website can use functions of the SlideShare service. These functions are offered by SlideShare Inc., 1 Montgomery St., Suite 1300, San Francisco, CA 94104, USA.</p>
    <p>» <a href="http://www.slideshare.net/privacy">Privacy policy</a></p>
    <h4>SoundCloud</h4>
    <p>This website can use functions of the SoundCloud service. These functions are offered by SoundCloud Ltd., Berners House, 47-48 Berners Street, London W1T 3NF, United Kingdom.</p>
    <p>» <a href="https://soundcloud.com/pages/privacy">Privacy policy</a></p>
    <h4>Twitter</h4>
    <p>
      This website can use functions of the Twitter service. The provider is Twitter Inc., 1355 Market Street, Suite 900, San Francisco, CA 94103, USA.
      Use of Twitter and its 'Retweet' function links the websites you visit to your Twitter account and disclosed that information to other users.
      In the process, data is also transmitted to Twitter. Please note that we as providers of the pages have no knowledge of what data is transmitted or of what Twitter does with it.
    </p>
    <p>» <a href="https://twitter.com/de/privacy">Privacy policy</a></p>
    <p>» <a href="https://twitter.com/settings/account"> Privacy settings</a></p>
    <h4>Vimeo</h4>
    <p>This website can use functions of the Vimeo service. These functions are provided by Vimeo, Inc., 555 West 18th Street, New York, New York 10011, USA.</p>
    <p>» <a href="https://vimeo.com/privacy">Privacy policy</a></p>
    <h4>Xing</h4>
    <p>
      This website can use functions of the Xing service. The provider is XING AG, Dammtorstrasse 29-32, 20354 Hamburg, Germany. A link is established to Xing servers every time you access one of our pages that contain Xing features.
      So far as we know, personal information is not stored. In particular, no IP addresses are stored, nor is usage behaviour analysed.
    </p>
    <p>» <a href="https://login.xing.com/?dest_url=https%3A%2F%2Fwww.xing.com%2Fsocial%2Fshare%2Fspi%3Fop%3Ddata_protection">Privacy policy</a></p>
    <h4>Yoast SEO</h4>
    <p>This website uses the Yoast SEO plugin. This is provided by Yoast BV, Don Emanuelstraat 3, 6602 GX Wijchen, The Netherlands, tel: +31 (0)24 82 00 337 (Chamber of Commerce / KvK: 55404367, VAT no: NL851692540B01).</p>
    <p>This plugin is responsible for the entire technical optimisation of our websites for search engines. It also plays a role in the development of content.</p>
    <p>» <a href="https://yoast.com/privacy-policy/">Privacy policy</a></p>
    <h4>YoutTube</h4>
    <p>This website can use functions of the YouTube service. These functions are provided by Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA.</p>
    <p>» <a href="https://policies.google.com/privacy">Privacy policy</a></p>
    <p>» <a href="https://www.google.com/account/about/?hl=de">Opt-out</a></p>
    <h2>Disclaimer</h2>
    <p>FHNW does not accept liability for any material or immaterial damage arising in connection with the use or non-use of the information offered, with the misuse of the connections or with technical faults.</p>
  </div>
</template>
